workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - google_play # Optional: if you have secrets
    triggering:
      events:
        - push
      branches:
        - main
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter packages pub get
      - name: Build Flutter web
        script: |
          flutter build web
      - name: Build Android APK
        script: |
          flutter build apk --release --no-shrink
    artifacts:
      - build/web/**
      - build/app/outputs/flutter-apk/app-release.apk
